export interface Testimoni {
  id: number;
  name: string;
  origin: string;
  package: string;
  rating: number;
  comment: string;
  description: string;
  image: string;
}

export const testimonials: Testimoni[] = [
  {
    id: 1,
    name: "Nadia Permata",
    origin: "Jakarta",
    package: "Honeymoon 2D1N Belitung Island",
    rating: 5,
    comment: "Tempatnya romantis banget!",
    description: "Pantai-pantainya bersih dan eksotis, pelayanan hotelnya pun luar biasa. Terima kasih Oceania, honeymoon kami jadi berkesan.",
    image: "/images/testimoni/woman.png",
  },
  {
    id: 2,
    name: "Jonathan Lee",
    origin: "Singapore",
    package: "Trip 2D1N Belitung Island",
    rating: 5,
    comment: "A relaxing and well-organized trip!",
    description: "The team was amazing! Every detail was handled perfectly, from hotel pickup to island tours. Definitely recommended!",
    image: "/images/testimoni/man.png",
  },
  {
    id: 3,
    name: "Tegar Adji",
    origin: "Lampung",
    package: "Honeymoon 3D2N Belitung Island",
    rating: 5,
    comment: "Pengalaman honeymoon yang luar biasa!",
    description: "Suasana romantis, pelayanan ramah, dan hotelnya indah banget. Terima kasih Oceania sudah bantu mewujudkan liburan impian kami.",
    image: "/images/testimoni/aji.jpeg",
  },
  {
    id: 4,
    name: "Siti Nurhaliza",
    origin: "Kuala Lumpur, Malaysia",
    package: "Family 3D2N Belitung Island",
    rating: 4,
    comment: "Pengalaman yang luar biasa di Belitung!",
    description: "Pantainya bersih, makanan sedap, dan tim guide sangat ramah. Kami pasti akan kembali lagi bersama keluarga besar.",
    image: "/images/testimoni/woman.png",
  },
  {
    id: 5,
    name: "Intan Maharani",
    origin: "Bandung",
    package: "Family 2D1N Belitung Island",
    rating: 5,
    comment: "Liburan singkat tapi berkesan!",
    description: "Meskipun cuma dua hari, semuanya tertata dengan baik. Guide-nya informatif dan sangat ramah. Recommended banget!",
    image: "/images/testimoni/woman.png",
  },
  {
    id: 6,
    name: "David Tan",
    origin: "Penang, Malaysia",
    package: "Trip 3D2N Belitung Island",
    rating: 4,
    comment: "Good itinerary and friendly guides!",
    description: "Our group enjoyed the snorkeling and cultural tours. Oceania made everything smooth and enjoyable.",
    image: "/images/testimoni/man.png",
  },
  {
    id: 7,
    name: "Rafi Antony",
    origin: "Yogyakarta",
    package: "Trip 3D2N Belitung Island",
    rating: 5,
    comment: "Liburan bersama Oceania benar-benar tak terlupakan!",
    description: "Semua destinasi sesuai ekspektasi, guide ramah, dan pelayanan sangat profesional. Sangat puas dan pasti akan merekomendasikan kepada teman-teman.",
    image: "/images/testimoni/rafi.jpeg",
  },
  {
    id: 8,
    name: "Mei Lin",
    origin: "Singapore",
    package: "Honeymoon 3D2N Belitung Island",
    rating: 5,
    comment: "Amazing experience, very well curated!",
    description: "The resort was beautiful and the staff from Oceania were so accommodating. Highly recommended for couples.",
    image: "/images/testimoni/woman.png",
  },
  {
    id: 9,
    name: "Bambang Sutrisno",
    origin: "Surabaya",
    package: "Family 3D2N Belitung Island",
    rating: 4,
    comment: "Keluarga saya sangat senang!",
    description: "Anak-anak menikmati setiap destinasi. Semua berjalan lancar dan aman. Saran saya, tambahkan pilihan kuliner lokal di paketnya.",
    image: "/images/testimoni/man.png",
  },
  {
    id: 10,
    name: "Farah Nabilah",
    origin: "Johor Bahru, Malaysia",
    package: "Family 2D1N Belitung Island",
    rating: 5,
    comment: "Wonderful family vacation!",
    description: "Everything was well-planned and our kids loved the beach activities. Thank you Oceania for the memorable experience.",
    image: "/images/testimoni/woman.png",
  },
  {
    id: 11,
    name: "Yoga Aditama",
    origin: "Salatiga",
    package: "Trip 3D2N Belitung Island",
    rating: 5,
    comment: "Pelayanan terbaik yang pernah saya dapatkan!",
    description: "Mulai dari penjemputan, destinasi, hingga makan siang semuanya tertata rapi. Cocok banget buat liburan bareng teman atau keluarga.",
    image: "/images/testimoni/yoga.jpeg",
  },
  {
    id: 12,
    name: "Ahmad Fadli",
    origin: "Singapore",
    package: "Hooping Island Belitung",
    rating: 4,
    comment: "Perfect island hopping experience!",
    description: "We visited beautiful small islands and enjoyed clear blue water. Oceania's service was excellent from start to finish.",
    image: "/images/testimoni/man.png",
  },
  {
    id: 13,
    name: "Reza Mahendra",
    origin: "Yogyakarta",
    package: "Hooping Island Belitung",
    rating: 5,
    comment: "Pulau-pulau kecilnya luar biasa indah!",
    description: "Air lautnya jernih banget, snorkelingnya seru, dan foto-fotonya instagramable. Terima kasih Oceania sudah atur trip ini.",
    image: "/images/testimoni/man.png",
  },
  {
    id: 14,
    name: "Henny Rubyjane",
    origin: "Jakarta",
    package: "Family 3D2N Belitung Island",
    rating: 5,
    comment: "Semuanya memuaskan!",
    description: "Mulai dari penginapan, makanan, hingga destinasi wisata semuanya sesuai ekspektasi. Cocok untuk liburan keluarga besar.",
    image: "/images/testimoni/heny.jpeg",
  },
  {
    id: 15,
    name: "Rangga Pratama",
    origin: "Bekasi",
    package: "Trip 2D1N Belitung Island",
    rating: 4,
    comment: "Trip singkat yang padat dan seru!",
    description: "Dalam dua hari bisa menjelajahi banyak tempat keren. Pelayanan cepat dan tidak membosankan. Akan ikut lagi untuk paket 3 hari!",
    image: "/images/testimoni/man.png",
  },
  {
    id: 16,
    name: "Lisa Anggraini",
    origin: "Semarang",
    package: "Honeymoon 3D2N Belitung Island",
    rating: 5,
    comment: "Romantis dan profesional!",
    description: "Dari awal booking sampai selesai trip, semuanya di-handle dengan baik. Terima kasih Oceania, pengalaman tak terlupakan!",
    image: "/images/testimoni/woman.png",
  },
];
